// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.24.0";

// src/lib/mcp/tools/list-recent-workouts.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z } from "npm:zod@^4.4.3";

// src/lib/mcp/tools/_supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.98.0";
function supabaseForUser(ctx) {
  const url = process.env.SUPABASE_URL;
  const key = process.env.SUPABASE_PUBLISHABLE_KEY ?? process.env.SUPABASE_ANON_KEY;
  return createClient(url, key, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
function unauth() {
  return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
}
function err(message) {
  return { content: [{ type: "text", text: message }], isError: true };
}
function ok(payload) {
  return {
    content: [{ type: "text", text: JSON.stringify(payload) }],
    structuredContent: { data: payload }
  };
}

// src/lib/mcp/tools/list-recent-workouts.ts
var list_recent_workouts_default = defineTool({
  name: "list_recent_workouts",
  title: "List recent workouts",
  description: "Returns the signed-in user's most recent workouts (id, name, started_at, finished_at, total sets).",
  inputSchema: {
    limit: z.number().int().min(1).max(50).optional().describe("Max workouts to return (default 10).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated()) return unauth();
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("workouts").select("id, name, started_at, finished_at, workout_sets(count)").eq("user_id", ctx.getUserId()).order("started_at", { ascending: false }).limit(limit ?? 10);
    if (error) return err(error.message);
    return ok(data);
  }
});

// src/lib/mcp/tools/get-workout.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z2 } from "npm:zod@^4.4.3";
var get_workout_default = defineTool2({
  name: "get_workout",
  title: "Get workout details",
  description: "Returns a single workout of the signed-in user, including all sets (exercise, weight, reps, rest_time).",
  inputSchema: {
    workout_id: z2.string().uuid().describe("Workout UUID.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ workout_id }, ctx) => {
    if (!ctx.isAuthenticated()) return unauth();
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("workouts").select("id, name, started_at, finished_at, notes, workout_sets(id, exercise_id, set_number, weight, reps, rest_time, created_at, exercises(name, muscle_group))").eq("id", workout_id).maybeSingle();
    if (error) return err(error.message);
    if (!data) return err("Workout not found");
    return ok(data);
  }
});

// src/lib/mcp/tools/search-exercises.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z3 } from "npm:zod@^4.4.3";
var search_exercises_default = defineTool3({
  name: "search_exercises",
  title: "Search exercise library",
  description: "Search the global exercise library by name substring, optionally filtered by muscle group.",
  inputSchema: {
    query: z3.string().min(1).describe("Substring to match against exercise name."),
    muscle_group: z3.string().optional().describe("Optional muscle group filter (e.g. Chest, Legs)."),
    limit: z3.number().int().min(1).max(50).optional()
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ query, muscle_group, limit }, ctx) => {
    if (!ctx.isAuthenticated()) return unauth();
    const supabase = supabaseForUser(ctx);
    let q = supabase.from("exercises").select("id, name, muscle_group, equipment, image_url").ilike("name", `%${query}%`).limit(limit ?? 20);
    if (muscle_group) q = q.eq("muscle_group", muscle_group);
    const { data, error } = await q;
    if (error) return err(error.message);
    return ok(data);
  }
});

// src/lib/mcp/tools/log-body-weight.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z4 } from "npm:zod@^4.4.3";
var log_body_weight_default = defineTool4({
  name: "log_body_weight",
  title: "Log body weight",
  description: "Record a new body-weight measurement for the signed-in user.",
  inputSchema: {
    weight_kg: z4.number().positive().describe("Body weight in kilograms."),
    note: z4.string().optional().describe("Optional note."),
    date: z4.string().optional().describe("Optional ISO date (YYYY-MM-DD). Defaults to today.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: false, openWorldHint: false },
  handler: async ({ weight_kg, note, date }, ctx) => {
    if (!ctx.isAuthenticated()) return unauth();
    const supabase = supabaseForUser(ctx);
    const row = {
      user_id: ctx.getUserId(),
      weight: weight_kg
    };
    if (note) row.notes = note;
    if (date) row.date = date;
    const { data, error } = await supabase.from("progress_entries").insert(row).select().maybeSingle();
    if (error) return err(error.message);
    return ok(data);
  }
});

// src/lib/mcp/tools/list-measurements.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z5 } from "npm:zod@^4.4.3";
var list_measurements_default = defineTool5({
  name: "list_measurements",
  title: "List body measurements",
  description: "Returns the signed-in user's recent progress entries (body weight and body measurements).",
  inputSchema: {
    limit: z5.number().int().min(1).max(100).optional()
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated()) return unauth();
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("progress_entries").select("*").eq("user_id", ctx.getUserId()).order("date", { ascending: false }).limit(limit ?? 20);
    if (error) return err(error.message);
    return ok(data);
  }
});

// src/lib/mcp/tools/get-fitness-stats.ts
import { defineTool as defineTool6 } from "npm:@lovable.dev/mcp-js@0.24.0";
var get_fitness_stats_default = defineTool6({
  name: "get_fitness_stats",
  title: "Get fitness stats",
  description: "Returns the signed-in user's current Fit Score, XP, level, and streaks.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) return unauth();
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("fitness_stats").select("*").eq("user_id", ctx.getUserId()).maybeSingle();
    if (error) return err(error.message);
    return ok(data);
  }
});

// src/lib/mcp/tools/list-today-nutrition.ts
import { defineTool as defineTool7 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z6 } from "npm:zod@^4.4.3";
var list_today_nutrition_default = defineTool7({
  name: "list_today_nutrition",
  title: "List today's food log",
  description: "Returns the signed-in user's food-log entries for a given day (defaults to today) and their macro totals.",
  inputSchema: {
    date: z6.string().optional().describe("ISO date (YYYY-MM-DD). Defaults to today (UTC).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ date }, ctx) => {
    if (!ctx.isAuthenticated()) return unauth();
    const day = date ?? (/* @__PURE__ */ new Date()).toISOString().slice(0, 10);
    const supabase = supabaseForUser(ctx);
    const start = `${day}T00:00:00.000Z`;
    const end = `${day}T23:59:59.999Z`;
    const { data, error } = await supabase.from("food_logs").select("*").eq("user_id", ctx.getUserId()).gte("created_at", start).lte("created_at", end).order("created_at", { ascending: false });
    if (error) return err(error.message);
    const totals = (data ?? []).reduce(
      (acc, row) => {
        acc.kcal += Number(row.kcal ?? 0);
        acc.protein += Number(row.protein ?? 0);
        acc.fat += Number(row.fat ?? 0);
        acc.carbs += Number(row.carbs ?? 0);
        return acc;
      },
      { kcal: 0, protein: 0, fat: 0, carbs: 0 }
    );
    return ok({ date: day, totals, entries: data });
  }
});

// src/lib/mcp/index.ts
var projectRef = "iuvwjsiwbpxbwenamzrj";
var mcp_default = defineMcp({
  name: "floer-fittrack-mcp",
  title: "Floer FitTrack",
  version: "0.1.0",
  instructions: "Tools to read and log the signed-in user's fitness data in Floer FitTrack: workouts, exercises, body measurements, fitness stats, and food logs. All actions run as the authenticated user under Row Level Security.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [
    list_recent_workouts_default,
    get_workout_default,
    search_exercises_default,
    log_body_weight_default,
    list_measurements_default,
    get_fitness_stats_default,
    list_today_nutrition_default
  ]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.24.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
